"$schema" = "node_modules/wrangler/config-schema.json"
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "tong"
compatibility_date = "2025-09-27"
main = "server/index.ts"

[limits]
subrequests = 10_000_000

[[routes]]
pattern = "tong.timothylin.me"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "LEXICON", class_name = "Lexicon" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Lexicon"]

[[d1_databases]]
binding = "DB"
database_name = "tong"
database_id = "86ec722c-cec2-45ea-8f2b-5ea45197e33c"

[[r2_buckets]]
bucket_name = "tong-documents"
binding = "DOCUMENTS"

[[workflows]]
name = "ingest-document"
binding = "INGEST_DOCUMENT_WORKFLOW"
class_name = "IngestDocumentWorkflow"

[workflows.limits]
steps = 25_000

[[workflows]]
name = "refresh-cedict"
binding = "REFRESH_CEDICT_WORKFLOW"
class_name = "RefreshCedictWorkflow"

[[workflows]]
name = "refresh-char-ids"
binding = "REFRESH_CHAR_IDS_WORKFLOW"
class_name = "RefreshCharIdsWorkflow"

[[vectorize]]
binding = "CHUNK_VECTORS"
index_name = "tong-doc-chunks"
remote = true

[ai]
binding = "AI"
remote = true

